### ISSUE TITLE
Buffer underrrun on certain hardware

### ISSUE THREAD

**Issue by dmik** [komh/kai#7] opened 2020-12-04 14:53 UTC
I have Asus K75VJ notebook and here is what happens when I run the demo in UNIAUD mode (with `set KAI_DEBUG=1`):

```
D:>kaidemo.exe DEMO1.WAV 2
Mode = UNIAUD, Available channels = 4, PDD Name = HDA Intel PCH
Number of channels = 1
Number of buffers = 2
Buffer size = 512
Silence = 80
ESC = quit, q = stop, w = play, e = pause, r = resume, +/- = volume up/down
UNIAUD: buffer underrun!l = [ 50%]
UNIAUD: EAGAIN : written = 1696 of 2048, state = 3
UNIAUD: EAGAIN : written = 1284 of 2048, state = 3
UNIAUD: EAGAIN : written = 1092 of 2048, state = 3
UNIAUD: EAGAIN : written = 1220 of 2048, state = 3
Status : [COMPLETED], vol = [ 50%]
```

As mentioned by @komh in https://github.com/bitwiseworks/qtwebengine-chromium-os2/issues/24#issuecomment-738607110, there is a buffer underrun indeed.

I can provide more info about my hardware and perform more tests on request.

**Comment by dmik** [comment] 2020-12-04 14:55
Note that I run ArcaOS 5 with all latest updates to the current date, including OS/2 Kernel 14.202 and `Uniaud-20200506.exe`.

**Comment by dmik** [comment] 2020-12-04 15:00
Note also that DART mode works even worse on this hardware, as described in the Chromium ticket above — OS/2 MMOS2 just stops calling the audio callback.

BTW, does kai need UNIAUD to work in DART mode? I guess not. So if the user has some hardware natively supported by OS/2, libkai will be able to serve it in DART mode. Just want to clarify that I get it right (w/o looking at the sources). And if yes,  will libkai select DART mode by default in such a case or UNIAUD will still be the default?

**Comment by komh** [comment] 2020-12-06 05:59
For buffer underrun, it at very first time is normal because it occurs when filling initial buffer. I'll improve this logic later.  If you see buffer underrun message in the middle of sound, it may generate choppy sounds because silence is inserted. 

The message of libkai is shown when callback does not fill an audio buffer, yet. So, it is not a problem of libkai nor Uniaud audio driver. Instead, your app should fill the buffer ASAP, maybe with large buffer, double buffering, or boosting a thread before kaiPlay() up to time critical priority, and restoreing after kaiPlay(), ...

If you hear choppy sounds in this issue ticket, it may be due to EAGAIN error, or although it's not showne in this issue ticket, worse is partial write. These occur in Uniaud audio driver itself, and should be fixed in Uniaud audio driver not in libkai.

For DART, libkai does not depend on Uniaud audio driver. If DART interface is supported by any audio driver, libkai can use DART mode. Actually, DART mode was developed with SBLive! driver. 

And libkai tries to use UNIAUD mode first in any cases. If it fails, libkai tries to use DART mode. As a result, if Uniaud audio driver is not installed, DART mode will be selected automatically.

Therefore, this ticket is not relevant to libkai. I'll close.

**Closed by komh** 2020-12-06 05:59 UTC

**Comment by dmik** [comment] 2020-12-07 16:14
> The message of libkai is shown when callback does not fill an audio buffer, yet. So, it is not a problem of libkai nor Uniaud audio driver. Instead, your app should fill the buffer ASAP, maybe with large buffer, double buffering, or boosting a thread before kaiPlay() up to time critical priority, and restoreing after kaiPlay(), ...

But it's not "my app", it's your test case. These buffer underruns are completely identical in both your test case (the output is above) and in Chromium. The buffer is filled up by Chromium as soon as the callback is called by libkai — it takes a few milliseconds, not more. And it is already double-buffered in Chromium and kaiPlay is called on a thread running on the highest priority. There is also a triple-buffering scheme but it doesn't make any difference. Also, as long as DART works (several seconds usually), there are *no* buffer underruns, all plays smoothly from both your test app and Chromium. So the problem is either in UNIAUD or in libkai.

Please let me know once/if you improve the logic — I will test it ASAP as right now this underrun is a bit annoying (and DART dies pretty fast).

**Comment by dmik** [comment] 2020-12-13 10:30
This is what I get from Chromium in UNIAUD mode, just in case:
```
UNIAUD: buffer underrun!
MIXER: buffer underrun!
UNIAUD: EAGAIN : written = 1028 of 2048, state = 3
UNIAUD: EAGAIN : written = 0 of 2048, state = 3
UNIAUD: EAGAIN : written = 1472 of 2048, state = 3
UNIAUD: EAGAIN : written = 1952 of 2048, state = 3
UNIAUD: EAGAIN : written = 1792 of 2048, state = 3
UNIAUD: EAGAIN : written = 1248 of 2048, state = 3
UNIAUD: EAGAIN : written = 1824 of 2048, state = 3
UNIAUD: EAGAIN : written = 1728 of 2048, state = 3
UNIAUD: EAGAIN : written = 612 of 2048, state = 3
UNIAUD: EAGAIN : written = 1860 of 2048, state = 3
UNIAUD: EAGAIN : written = 0 of 2048, state = 3
UNIAUD: EAGAIN : written = 1248 of 2048, state = 3
UNIAUD: EAGAIN : written = 768 of 2048, state = 3
```

**Comment by dmik** [comment] 2020-12-13 10:38
This is what I get from Chromium in UNIAUD mode, just in case:
```
[19833:7:1213/132503.838000:VERBOSE1:audio_manager_os2.cc(64)] input_params rate 48000, layout 3, channels 2, frames per buf 1024
[19833:7:1213/132503.838000:VERBOSE1:audio_manager_os2.cc(68)] kai mode UniAud, max channels 4, name HDA Intel PCH
[19833:7:1213/132503.842000:VERBOSE1:audio_manager_os2.cc(93)] optimal rate 48000, channels 2, bufsize 2048, frames per buf 512
UNIAUD: buffer underrun!
MIXER: buffer underrun!
UNIAUD: EAGAIN : written = 1028 of 2048, state = 3
UNIAUD: EAGAIN : written = 0 of 2048, state = 3
UNIAUD: EAGAIN : written = 1472 of 2048, state = 3
UNIAUD: EAGAIN : written = 1952 of 2048, state = 3
UNIAUD: EAGAIN : written = 1792 of 2048, state = 3
UNIAUD: EAGAIN : written = 1248 of 2048, state = 3
UNIAUD: EAGAIN : written = 1824 of 2048, state = 3
UNIAUD: EAGAIN : written = 1728 of 2048, state = 3
UNIAUD: EAGAIN : written = 612 of 2048, state = 3
UNIAUD: EAGAIN : written = 1860 of 2048, state = 3
UNIAUD: EAGAIN : written = 0 of 2048, state = 3
UNIAUD: EAGAIN : written = 1248 of 2048, state = 3
UNIAUD: EAGAIN : written = 768 of 2048, state = 3
```
And here's DART mode:
```
[19858:7:1213/133141.717000:VERBOSE1:audio_manager_os2.cc(64)] input_params rate 48000, layout 3, channels 2, frames per buf 1024
[19858:7:1213/133141.719000:VERBOSE1:audio_manager_os2.cc(68)] kai mode DART, max channels 4, name OS/2 Universal Audio: Wave
[19858:7:1213/133141.723000:VERBOSE1:audio_manager_os2.cc(93)] optimal rate 48000, channels 2, bufsize 8192, frames per buf 2048
DART: buffer underrun!
DART: buffer underrun!
MIXER: buffer underrun!

DART error(15ed):Insufficient buffer size specified.
[19858:7:1213/133141.736000:ERROR:audio_output_stream_os2.cc(60)] kaiPlay(9db1a0) returned 5613
```
And here is KAIDEMO DEMO1.WAV output in DART mode:
```
D:>kaidemo.exe DEMO1.WAV
Mode = DART, Available channels = 4, PDD Name = OS/2 Universal Audio: Wave
Number of channels = 1
Number of buffers = 2
Buffer size = 2048
Silence = 80
ESC = quit, q = stop, w = play, e = pause, r = resume, +/- = volume up/down
DART: buffer underrun!
MIXER: buffer underrun!
DART: buffer underrun!

DART error(15ed):Insufficient buffer size specified.
Status : [  STOPPED], vol = [ 50%]
```
Same thing. So it's not something Chromium specific.

**Comment by komh** [comment] 2020-12-13 12:13
As I said, initial buffer underruns are not problems at all. If you experience stuttering or choppy sounds, then the problem is frequent EAGAIN which is a cause in UNIAUD audio driver. UNIAUD APIs of UNIAUD audio driver have been broken for a long time. For this, See http://trac.netlabs.org/uniaud/ticket/191 and http://trac.netlabs.org/uniaud/ticket/231.

For DART mode, it's well-known error of UNIAUD audio driver. Usually, it occurs when using DART mode after using UNIAUD mode several times. Worse is that a crash can occur.

Nowadays, DART interface of UNIAUD audio driver is more stable than UNIAUD interface which seems to be not maintained. Therefore, you'd better use DART mode if possible with SET KAI_AUTOMODE=DART.

**Comment by dmik** [comment] 2020-12-13 12:16
Ok, thanks for additional info. It's clear about DART being more stable but it simply does not work here (the callback is not called at all, so not an option). Anyway, my point was to rule out Chromium code for now so I'm kind of satisfied with your explanation.

**Comment by komh** [comment] 2020-12-14 10:54
For DART problems, frequent pause and resume operation, play and stop operation, and open and close operation may cause a stream to be block, that is, as you said, a callback is not called any more. 

This was observed very frequently when porting OpenDUNE. To workaround, I've introduced dummy stream filled with zero as a main stream. See https://github.com/OpenDUNE/OpenDUNE/blob/master/src/audio/dsp_kai.c.

But, this approach may lock audio instance because the dummy stream should be maintained as long as an app running.

Anyway, thanks for your hard work!!!

**Comment by dmik** [comment] 2020-12-14 13:05
Thanks, you are welcome :)
